const CLASSNAME_HORIZONTAL_INDICATOR = "horizontal-indicator";
const CLASSNAME_QUESTION_BOX = "question-box";
const CLASSNAME_QUESTION_BOXES_CONTAINER = "question-boxes-container";

export {
  CLASSNAME_HORIZONTAL_INDICATOR,
  CLASSNAME_QUESTION_BOX,
  CLASSNAME_QUESTION_BOXES_CONTAINER,
};
