const DEFAULT_BORDER_RADIUS_UNIT = 4; // 단위: px
const DEFAULT_PADDING_UNIT = 8; // 단위: px
const DEFAULT_MARGIN_UNIT = 8; // 단위: px

export {
  DEFAULT_BORDER_RADIUS_UNIT,
  DEFAULT_PADDING_UNIT,
  DEFAULT_MARGIN_UNIT,
};
